# All configurations can be found here
# https://starship.rs/config/

##############
# Formatting #
##############

format = """
[$os](bold red) $username@$hostname in $directory
[┣❰](bold red) $fill [❱](bold red)
[┗❱](bold red) """

add_newline = true

###########
# Options #
###########

#####
# A #
#####

#####
# B #
#####

#####
# C #
#####

#####
# D #
#####
[directory]
disabled = false
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold red"
truncation_length = 4
truncate_to_repo = true
read_only = " 󰈡"
read_only_style = "bold red"
truncation_symbol = "..."
before_repo_root_style = ''
repo_root_style = ''
repo_root_format = "'[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
home_symbol = "~"
use_os_path_sep = true

#####
# E #
#####

#####
# F #
#####
[fill]
disabled = false
style = ""
symbol = " "

#####
# G #
#####

#####
# H #
#####
[hostname]
disabled = false
format = '$ssh_symbol$hostname'
style = ""
#detect_env_vars = []
ssh_only = false
ssh_symbol = "[󰣀](bold red)"
trim_at = '.'

#####
# I #
#####

#####
# J #
#####

#####
# K #
#####

#####
# L #
#####

#####
# M #
#####

#####
# N #
#####

#####
# O #
#####
[os]
disabled = false
format = '$symbol'
style = ''

[os.symbols]
Alpaquita = '󰯬'
Alpine = ''
Amazon = ''
Android = ''
Arch = '󰣇'
Artix = ''
CentOS = ''
Debian = '󰣚'
DragonFly = ''
Emscripten = '󱨦'
EndeavourOS = ''
Fedora = '󰣛'
FreeBSD = '󰣠'
Garuda = ''
Gentoo = '󰣨'
HardenedBSD = ''
Illumos = ''
Linux = ''
Mabox = '󰬔'
Macos = ''
Manjaro = '󱘊'
Mariner = '󰍶'
MidnightBSD = '󰄛'
Mint = '󰣭'
NetBSD = '󰈿'
NixOS = '󱄅'
OpenBSD = ''
OpenCloudOS = '󰅟'
openEuler = '󰬌'
openSUSE = ''
OracleLinux = ''
Pop = ''
Raspbian = ''
Redhat = '󱄛'
RedHatEnterprise = ''
Redox = '󱥸'
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

#####
# P #
#####

#####
# Q #
#####

#####
# R #
#####

#####
# S #
#####

#####
# T #
#####

#####
# U #
#####
[username]
disabled = false
format = '[$user]($style)'
style_user = 'bold white'
style_root = 'bold red'
show_always = true

#####
# V #
#####

#####
# W #
#####

#####
# X #
#####

#####
# Y #
#####

#####
# Z #
#####
